첫페이지 view 작성
hufslion10th/welcome_kit pull request #4
Opened 2022-03-09 15:06 UTC by JungWooJin97

## 개요
PR을 요청하는 이유를 요약해서 적어주세요.
첫페이지 view 작성하여 PR드립니다.

## 작업사항
작업한 내용을 이해하기 쉽게 적어주세요: 가능하면 커밋단위로
배경제작하였고, js 사용하여 애니메이션 구현하였습니다.
화면에 fade in 효과, congratulation효과, text(left to right)효과 적용하였습니다.

## 변경로직
변경 전, 후를 비교하여 적어주세요.
x

## 사용방법
해당 기능을 사용하기 위한 방법을 알려주세요.
window 오픈시 실행되도록 작성하였습니다.

## 기타
남기고 싶은 말 또는 의논사항을 적어주세요.
버튼은 적절한 디자인 찾아서 첨가하여 다시 PR드리겠습니다.

2022-03-09 15:10 UTC, 4923 commented
우선 폰트는 [스포카 산스 네오](https://spoqa.github.io/spoqa-han-sans/) 사용하려고 합니다.
자세한 코드 리뷰는 경준님이 해주시는게 좋겠네요.

고생 많으셨습니다!

2022-03-09 15:17 UTC, 4923 reviewed
우선 폰트는 [스포카 산스 네오](https://spoqa.github.io/spoqa-han-sans/) 사용하려고 합니다.
자세한 코드 리뷰는 경준님이 해주시는게 좋겠네요.

### 요청사항 세가지 있습니다.
1. PR 생성하신 후 assignee에는 본인을, reviewer에는 코드 확인이 필요한 사람을 할당해주세요!

2. 커밋메시지
다음부터 커밋 메시지는 `타입 내용` 으로 통일해주시면 좋겠습니다. 그리고 작업 내용도 커밋메시지 본문에 작성해주세요!
- [커밋메시지 타입 참고](https://overcome-the-limits.tistory.com/entry/협업-협업을-위한-기본적인-git-커밋컨벤션-설정하기)

3. 페이지명
그리고 페이지명은 화면흐름도 작성되는대로 적당히 바꾸는게 좋겠습니다.  전반적으로 파일명/함수명/커밋만 봐도 어떤 작업을 했는지 확인할 수 있으면 협업이 더 편리할 것 같아요~
이건 제가 어서 일 끝내고 알려드릴게요!

고생 많으셨습니다! 
코드는 경준님이 approve 하시는게 맞다고 생각해서 저는 comment만 남깁니다.

2022-03-09 15:17 UTC, 4923 commented on project/index2.html
> +</html>
`index2.html` 은 `index.html` 과 어떻게 다른가요? js 효과만 넣기위해 사용하는 html 인가요?

2022-03-09 15:29 UTC, JungWooJin97 commented on project/index2.html
> +</html>
넵 요청사항 확인했습니다!
index2.html은 제가 다른 애니메이션 실험하던 페이지였는데 지우는걸 깜빡했네요...
말씀하신대로 쟈스는 경준님께 부탁드리겠습니다.
감사합니다!

2022-03-10 06:35 UTC, Parkjju requested changes
수고하셨어요 우진님 💯 애니메이션 너무 잘 구하셨네요 :) 
몇 가지 의견 남겨드렸는데 확인 한번 해주시면 감사하겠습니다 ~~~
횡스크롤 관련해서 전체적으로 사이즈 조정해봤습니다~!

2022-03-10 06:35 UTC, Parkjju commented on project/style.css
> +.container {
페이지 진입 시 횡스크롤이 생겨서 전체적인 이미지 크기를 줄여봤습니다 👍 
```css
  box-sizing: border-box;
  width: 100%;
```

2022-03-10 06:35 UTC, Parkjju commented on project/index.html
> +    <div class="fade-in-box" style="background-image: url(static/img/lion_background.jpg); background-size: cover; width: 105rem; height: 52rem;">
```html
<div
        class="fade-in-box"
        style="
          background-image: url(static/img/lion_background.jpg);
          background-size: cover;
          width: 100%;
          height: 52rem;
        "
      >
```
`fade-in-box` 클래스의 이미지파일 `width`값도 100%로 맞춰서 횡스크롤 없애봤습니다 👍

2022-03-10 06:35 UTC, Parkjju commented on project/index.html
> +      <div class="text" style="position: absolute; background-color: rgb(0, 0, 0); margin-top: 10rem; margin-left: 60rem; width:40rem; height: 30rem; padding-top: 8rem; color: white; text-align: cent
```html
        <div
          class="text"
          style="
            position: absolute;
            background-color: rgb(0, 0, 0);
            margin-top: 5rem;
            margin-left: 50rem;
            width: 35rem;
            height: 20rem;
            padding-top: 8rem;
            color: white;
            text-align: center;
          "
        >
```
백그라운드 이미지 & confetti 컨테이너 사이즈에 맞춰서 텍스트 박스도 크기 줄여봤습니다~ 👍 `height` , `width`값만 보시면 돼요!

2022-03-10 16:05 UTC, merged